[ Feat ] 설정, 결제 화면
Team-Shaka/Briefing-Android-Legacy pull request #47
Opened 2023-11-19 17:50 UTC by kimwest00

## ‼️ 관련 이슈
- #42 
- Setting쪽 component - layout 분리 #43 

## ✨ PR Point
> Setting, Premium 2.0 UI 업데이트 작업
1.  Layout과 Component를 분리했습니다. 화면의 전체적인 Composable만 Screen 파일에 남겨두고 나머지는 component 패키지에 분리하였고, 되도록 파일로 component를 분리하려고 했습니다.
2. CommonHeader등 공통적으로 쓰는 component는 presentation 하위의 패키지에 위치하였습니다

## To Reviewers
> 참고사항및 특이점이 있으면 적어주세요
1. 현재 Design System 구축이전이여서, Black,White, SubText2, **MainPrimary6** 등만을 현재 figma값으로 업데이트해두고, 
나머지 속성은 그대로 두었습니다. 특히 Type쪽은 MaterialTheme의 속성값을 사용하고있어 사용이 어려우니, detail 작업하셨던것처럼 **추후에 Design System을 적용**하는식으로 작업해주시면 될 것 같습니다.

2. 현재 Setting 이외의 화면은 레이아웃 위젯 분리 작업을 아직 못해서 월요일~화요일 중으로 분리해서 issue close 히도록 하겠습니다!

2023-11-24 22:45 UTC, gomsang requested changes

2023-11-24 22:45 UTC, gomsang commented on app/src/main/java/com/dev/briefing/presentation/theme/component/CommonHeader.kt
> +@Preview
Preview 에서 실제 Typography 나 Color 가 적용되려면 Theme 로 한번 감싸줘야 해서, CommonHeaderPreview 를 따로 만들어서 빼는게 더 나을 것 같아요

2023-11-24 22:46 UTC, gomsang commented
해당 PR 이후로 디자인 시스템에서 Typography 네이밍이 일부 변경된 것 같습니다. 제가 너무 늦게 확인한 탓인거 같은데 이 부분만 다시 확인하셔서 수정부탁드립니다.

2023-11-24 22:48 UTC, gomsang commented
수고 많으셨습니다. 확인하다 보니 PR 이후로 디자인 시스템에서 Typography 네이밍 수정 된 부분도 있고 자잘하게 변경된것 같아서 이후로 제가 작업하면서 수정할 수 있도록 하겠습니다 👍

2023-11-25 03:53 UTC, kimwest00 commented on app/src/main/java/com/dev/briefing/presentation/theme/component/CommonHeader.kt
> +@Preview
앗 기존에 사용하던 Color, typo를 변경하는데에 시간이 좀 오래걸려서 
Preview의 경우 개발하면서 수정해도 되는부분이라고 생각되어 아직 작업 하지않았습니다!
좋습니당🙆‍♂️🙆‍♂️

2023-11-25 04:21 UTC, kimwest00 commented
- figma상에서 typo 변수 변경사항 적용
- Preview 수정
위의 2가지 반영했습니다~! @gomsang

2023-11-26 08:46 UTC, gomsang approved these changes

2023-11-26 13:40 UTC, merged